var freeimage = require(__dirname + "/../build/Release/image");

exports.Image = new freeimage.FreeImage();

//image formats
exports.Image.FIF_UNKNOWN = -1;
exports.Image.FIF_BMP   = 0;
exports.Image.FIF_ICO   = 1;
exports.Image.FIF_JPEG  = 2;
exports.Image.FIF_JNG   = 3;
exports.Image.FIF_KOALA = 4;
exports.Image.FIF_LBM   = 5;
exports.Image.FIF_IFF = exports.Image.FIF_LBM;
exports.Image.FIF_MNG   = 6;
exports.Image.FIF_PBM   = 7;
exports.Image.FIF_PBMRAW  = 8;
exports.Image.FIF_PCD   = 9;
exports.Image.FIF_PCX   = 10;
exports.Image.FIF_PGM   = 11;
exports.Image.FIF_PGMRAW  = 12;
exports.Image.FIF_PNG   = 13;
exports.Image.FIF_PPM   = 14;
exports.Image.FIF_PPMRAW  = 15;
exports.Image.FIF_RAS   = 16;
exports.Image.FIF_TARGA = 17;
exports.Image.FIF_TIFF  = 18;
exports.Image.FIF_WBMP  = 19;
exports.Image.FIF_PSD   = 20;
exports.Image.FIF_CUT   = 21;
exports.Image.FIF_XBM   = 22;
exports.Image.FIF_XPM   = 23;
exports.Image.FIF_DDS   = 24;
exports.Image.FIF_GIF   = 25;
exports.Image.FIF_HDR   = 26;
exports.Image.FIF_FAXG3 = 27;
exports.Image.FIF_SGI   = 28;
exports.Image.FIF_EXR   = 29;
exports.Image.FIF_J2K   = 30;
exports.Image.FIF_JP2   = 31;
exports.Image.FIF_PFM   = 32;
exports.Image.FIF_PICT  = 33;
exports.Image.FIF_RAW   = 34;

//Load / Save flag constants -----------------------------------------------
exports.Image.BMP_DEFAULT         =0;
exports.Image.BMP_SAVE_RLE        =1;
exports.Image.CUT_DEFAULT         =0;
exports.Image.DDS_DEFAULT     =0;
exports.Image.EXR_DEFAULT     =0;   // save data as half with piz-based wavelet compression
exports.Image.EXR_FLOAT     =0x0001;  // save data as float instead of as half (not recommended)
exports.Image.EXR_NONE      =0x0002;  // save with no compression
exports.Image.EXR_ZIP       =0x0004;  // save with zlib compression, in blocks of 16 scan lines
exports.Image.EXR_PIZ       =0x0008;  // save with piz-based wavelet compression
exports.Image.EXR_PXR24     =0x0010;  // save with lossy 24-bit float compression
exports.Image.EXR_B44       =0x0020;  // save with lossy 44% float compression - goes to 22% when combined with EXR_LC
exports.Image.EXR_LC        =0x0040;  // save images with one luminance and two chroma channels, rather than as RGB (lossy compression)
exports.Image.FAXG3_DEFAULT   =0;
exports.Image.GIF_DEFAULT     =0;
exports.Image.GIF_LOAD256     =1;   // Load the image as a 256 color image with ununsed palette entries, if it's 16 or 2 color
exports.Image.GIF_PLAYBACK    =2;   // 'Play' the GIF to generate each frame (as 32bpp) instead of returning raw frame data when loading
exports.Image.HDR_DEFAULT     =0;
exports.Image.ICO_DEFAULT     =0;
exports.Image.ICO_MAKEALPHA   =1;   // convert to 32bpp and create an alpha channel from the AND-mask when loading
exports.Image.IFF_DEFAULT     =0;
exports.Image.J2K_DEFAULT     =0;   // save with a 16:1 rate
exports.Image.JP2_DEFAULT     =0;   // save with a 16:1 rate
exports.Image.JPEG_DEFAULT    =0;   // loading (see JPEG_FAST); saving (see JPEG_QUALITYGOOD|JPEG_SUBSAMPLING_420)
exports.Image.JPEG_FAST       =0x0001;  // load the file as fast as possible, sacrificing some quality
exports.Image.JPEG_ACCURATE   =0x0002;  // load the file with the best quality, sacrificing some speed
exports.Image.JPEG_CMYK     =0x0004;  // load separated CMYK "as is" (use | to combine with other load flags)
exports.Image.JPEG_EXIFROTATE   =0x0008;  // load and rotate according to Exif 'Orientation' tag if available
exports.Image.JPEG_QUALITYSUPERB  =0x80;  // save with superb quality (100:1)
exports.Image.JPEG_QUALITYGOOD    =0x0100;  // save with good quality (75:1)
exports.Image.JPEG_QUALITYNORMAL  =0x0200;  // save with normal quality (50:1)
exports.Image.JPEG_QUALITYAVERAGE =0x0400;  // save with average quality (25:1)
exports.Image.JPEG_QUALITYBAD     =0x0800;  // save with bad quality (10:1)
exports.Image.JPEG_PROGRESSIVE  =0x2000;  // save as a progressive-JPEG (use | to combine with other save flags)
exports.Image.JPEG_SUBSAMPLING_411 =0x1000;   // save with high 4x1 chroma subsampling (4:1:1) 
exports.Image.JPEG_SUBSAMPLING_420 =0x4000;   // save with medium 2x2 medium chroma subsampling (4:2:0) - default value
exports.Image.JPEG_SUBSAMPLING_422 =0x8000;   // save with low 2x1 chroma subsampling (4:2:2) 
exports.Image.JPEG_SUBSAMPLING_444 =0x10000;  // save with no chroma subsampling (4:4:4)
exports.Image.KOALA_DEFAULT       =0;
exports.Image.LBM_DEFAULT         =0;
exports.Image.MNG_DEFAULT         =0;
exports.Image.PCD_DEFAULT         =0;
exports.Image.PCD_BASE            =1;   // load the bitmap sized 768 x 512
exports.Image.PCD_BASEDIV4        =2;   // load the bitmap sized 384 x 256
exports.Image.PCD_BASEDIV16       =3;   // load the bitmap sized 192 x 128
exports.Image.PCX_DEFAULT         =0;
exports.Image.PFM_DEFAULT         =0;
exports.Image.PICT_DEFAULT        =0;
exports.Image.PNG_DEFAULT         =0;
exports.Image.PNG_IGNOREGAMMA   =1;   // loading: avoid gamma correction
exports.Image.PNG_Z_BEST_SPEED      =0x0001;  // save using ZLib level 1 compression flag (default value is 6)
exports.Image.PNG_Z_DEFAULT_COMPRESSION =0x0006;  // save using ZLib level 6 compression flag (default recommended value)
exports.Image.PNG_Z_BEST_COMPRESSION    =0x0009;  // save using ZLib level 9 compression flag (default value is 6)
exports.Image.PNG_Z_NO_COMPRESSION    =0x0100;  // save without ZLib compression
exports.Image.PNG_INTERLACED        =0x0200;  // save using Adam7 interlacing (use | to combine with other save flags)
exports.Image.PNM_DEFAULT         =0;
exports.Image.PNM_SAVE_RAW        =0;       // If set the writer saves in RAW format (i.e. P4, P5 or P6)
exports.Image.PNM_SAVE_ASCII      =1;       // If set the writer saves in ASCII format (i.e. P1, P2 or P3)
exports.Image.PSD_DEFAULT         =0;
exports.Image.RAS_DEFAULT         =0;
exports.Image.RAW_DEFAULT         =0;   // load the file as linear RGB 48-bit
exports.Image.RAW_PREVIEW     =1;   // try to load the embedded JPEG preview with included Exif Data or default to RGB 24-bit
exports.Image.RAW_DISPLAY     =2;   // load the file as RGB 24-bit
exports.Image.SGI_DEFAULT     =0;
exports.Image.TARGA_DEFAULT       =0;
exports.Image.TARGA_LOAD_RGB888   =1;       // If set the loader converts RGB555 and ARGB8888 -> RGB888.
exports.Image.TIFF_DEFAULT        =0;
exports.Image.TIFF_CMYK     =0x0001;  // reads/stores tags for separated CMYK (use | to combine with compression flags)
exports.Image.TIFF_PACKBITS       =0x0100;  // save using PACKBITS compression
exports.Image.TIFF_DEFLATE        =0x0200;  // save using DEFLATE compression (a.k.a. ZLIB compression)
exports.Image.TIFF_ADOBE_DEFLATE  =0x0400;  // save using ADOBE DEFLATE compression
exports.Image.TIFF_NONE           =0x0800;  // save without any compression
exports.Image.TIFF_CCITTFAX3    =0x1000;  // save using CCITT Group 3 fax encoding
exports.Image.TIFF_CCITTFAX4    =0x2000;  // save using CCITT Group 4 fax encoding
exports.Image.TIFF_LZW      =0x4000;  // save using LZW compression
exports.Image.TIFF_JPEG     =0x8000;  // save using JPEG compression
exports.Image.WBMP_DEFAULT        =0;
exports.Image.XBM_DEFAULT     =0;
exports.Image.XPM_DEFAULT     =0;
